### ISSUE TITLE
Importing 0 groups.

### ISSUE THREAD

**Issue by rainfarmer** [bdharrington7/nodebb-plugin-import-vanilla#9]
Hi, I've got the importer running but it freezes at importing groups:
I get this response from the client log:

    current phase: groupsImportDone
    Importing 0/0 groups took: 0.00 seconds
    Importing 0 groups.
    current phase: groupsImportStart
    current phase: resetGlobalsDone
    current phase: deleteTmpImportedSetsAndObjectsDone
    current phase: deleteTmpImportedSetsAndObjectsStart
    current phase: resetGlobalsStart
    current phase: purgeMessagesDone
    current phase: purgeMessagesStart
    current phase: purgeUsersDone
    current phase: purgeUsersStart
    current phase: purgeCategories+Topics+PostsDone
    current phase: purgeCategories+Topics+PostsStart

There is an error on the server log:

    23/9 01:29 [18747] - [31merror [39m: Error: ER_ACCESS_DENIED_ERROR: Access denied for   user 'username'@'wrongserver' (using password: YES)
I can see that it's using the local server ip, which is wrong. In the plugin menu, I entered a mysql address for a DB on a different server. I can connect to the mysql server via terminal, using:

     mysql -u user -h mysql.server.com -p

NodeBB v0.7.0
Node.js v0.11.16
Vanilla v2.1
Using the master version of nodebb-plugin-import-vanilla and nodebb-plugin-import

I used correct DB login and prefix GDN_
Everything else is default settings.
Any ideas?

Note: I think this is more an issue with nodebb-plugin-import, so I'm moving this question to there.
Sorry for posting in wrong area.

**Comment by bdharrington7** [comment]
this is an effect of https://github.com/akhoury/nodebb-plugin-import/issues/132, correct?

**Comment by rainfarmer** [comment]
Ya like I said I think it's more related to the nodebb-plugin-import plugin.
But I'm not sure. If you don't think it belongs here, feel free to delete this issue.

**Comment by bdharrington7** [comment]
This has been resolved, the issue resolution can be viewed above
